In [4]:
import pandas as pd
import numpy as np
data = np.array(['g','e','e','k','s'])

In [5]:
s = pd.Series(data)
print("Pandas Series:",s)
print(type(s))

Pandas Series: 0    g
1    e
2    e
3    k
4    s
dtype: object
<class 'pandas.core.series.Series'>

In [6]:
a = [1,2,3,4,5]
# print(a)
df = pd.DataFrame(a)
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [7]:
a= {
    "Fruits":["Apple","Kiwi","Grapes"],
    "Price": [80,90,100]
}
#print(a)
df = pd.DataFrame(a)
print(df)
#df.to_csv("Fruits.csv")
df.to_csv("Fruits.csv",index=False)

   Fruits  Price
0   Apple     80
1    Kiwi     90
2  Grapes    100

In [10]:
df = pd.read_csv("Netflix_titles_dataset.csv")
print(df)

      show_id     type                          title  \
0      s10651    Movie             Garfield Gets Real
1       s2042    Movie                    Sky on Fire
2       s8669    Movie                     Alien Xmas
3       s1115    Movie                       Arthur
4      s13903  TV Show                           GLOW
...       ...      ...                            ...
19995  s11285    Movie            Muppets Most Wanted
19996  s11965    Movie    R.L. Stine's Mostly Ghostly
19997   s5391  TV Show                          Vexed
19998    s861    Movie  Chhota Bheem: Bheem vs Aliens
19999  s15796    Movie             Lying and Stealing

                            director  \
0      Mark A.Z. Dippé, Kyung Ho Lee
1                          Ringo Lam
2                     Stephen Chiodo
3                                NaN
4                                NaN
...                              ...
19995                            NaN
19996                Richard Correll
19997                            NaN
19998                  Rajiv Chilaka
19999                   Matt Aselton

                                                    cast           country  \
0      Frank Welker, Wally Wingert, Gregg Berger, Jen...     United States
1      Daniel Wu, Joseph Chang, Amber Kuo, Zhang Jing...  China, Hong Kong
2      Keythe Farley, Dee Bradley Baker, Kaliayh Rham...     United States
3                                                    NaN     United States
4      Alison Brie, Betty Gilpin, Marc Maron, Britney...     United States
...                                                  ...               ...
19995  Ricky Gervais, Ty Burrell, Tina Fey, Kermit th...     United States
19996  Madison Pettis, Sterling Beaumon, Luke Benward...     United States
19997  Toby Stephens, Miranda Raison, Lucy Punch, Nic...    United Kingdom
19998  Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...               NaN
19999  Theo James, Emily Ratajkowski, Fred Melamed, E...     United States

              date_added  release_year rating   duration
0        January 1, 2020        2007.0   TV-Y     78 min
1         August 5, 2017        2016.0  TV-MA        NaN
2      November 20, 2020        2020.0   TV-Y     42 min
3          April 1, 2019        2011.0  PG-13    110 min
4         August 9, 2019        2019.0    NaN  3 Seasons
...                  ...           ...    ...        ...
19995  September 1, 2020        2014.0     PG    110 min
19996     August 1, 2018        2008.0     PG     98 min
19997                NaN           NaN    NaN  2 Seasons
19998      July 22, 2021           NaN  TV-Y7     69 min
19999      June 30, 2021        2019.0    NaN        NaN

[20000 rows x 10 columns]

In [13]:
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration
0,s10651,Movie,Garfield Gets Real,"Mark A.Z. Dippé, Kyung Ho Lee","Frank Welker, Wally Wingert, Gregg Berger, Jen...",United States,"January 1, 2020",2007.0,TV-Y,78 min
1,s2042,Movie,Sky on Fire,Ringo Lam,"Daniel Wu, Joseph Chang, Amber Kuo, Zhang Jing...","China, Hong Kong","August 5, 2017",2016.0,TV-MA,NaN
2,s8669,Movie,Alien Xmas,Stephen Chiodo,"Keythe Farley, Dee Bradley Baker, Kaliayh Rham...",United States,"November 20, 2020",2020.0,TV-Y,42 min
3,s1115,Movie,Arthur,NaN,NaN,United States,"April 1, 2019",2011.0,PG-13,110 min
4,s13903,TV Show,GLOW,NaN,"Alison Brie, Betty Gilpin, Marc Maron, Britney...",United States,"August 9, 2019",2019.0,NaN,3 Seasons

In [15]:
df.tail(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration
19995,s11285,Movie,Muppets Most Wanted,NaN,"Ricky Gervais, Ty Burrell, Tina Fey, Kermit th...",United States,"September 1, 2020",2014.0,PG,110 min
19996,s11965,Movie,R.L. Stine's Mostly Ghostly,Richard Correll,"Madison Pettis, Sterling Beaumon, Luke Benward...",United States,"August 1, 2018",2008.0,PG,98 min
19997,s5391,TV Show,Vexed,NaN,"Toby Stephens, Miranda Raison, Lucy Punch, Nic...",United Kingdom,NaN,NaN,NaN,2 Seasons
19998,s861,Movie,Chhota Bheem: Bheem vs Aliens,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",NaN,TV-Y7,69 min
19999,s15796,Movie,Lying and Stealing,Matt Aselton,"Theo James, Emily Ratajkowski, Fred Melamed, E...",United States,"June 30, 2021",2019.0,NaN,NaN

In [16]:
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration
6775,s10213,Movie,1898: Our Last Men in the Philippines,Salvador Calvo,"Luis Tosar, Javier Gutiérrez, Álvaro Cervantes...",Spain,"June 2, 2017",NaN,R,130 min
4593,s6904,TV Show,The Standups,NaN,NaN,NaN,NaN,NaN,TV-MA,2 Seasons
13689,s2522,Movie,I Will Follow,Ava DuVernay,"Salli Richardson-Whitfield, Michole Briana Whi...",United States,"May 20, 2020",2010.0,TV-14,80 min
9863,s15053,Movie,Forbidden Planet,Fred M. Wilcox,NaN,United States,"November 1, 2019",NaN,G,98 min
16140,s7610,Movie,Metro,NaN,"Yogi Babu, Bobby Simha, Shirish",India,"April 1, 2018",2016.0,TV-14,NaN

In [18]:
df.shape

(20000, 10)

In [19]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration'],
      dtype='object')

In [20]:
df.index

RangeIndex(start=0, stop=20000, step=1)

In [21]:
df.dtypes

show_id          object
type             object
title            object
director         object
cast             object
country          object
date_added       object
release_year    float64
rating           object
duration         object
dtype: object

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       20000 non-null  object
 1   type          20000 non-null  object
 2   title         20000 non-null  object
 3   director      12136 non-null  object
 4   cast          15964 non-null  object
 5   country       14570 non-null  object
 6   date_added    16371 non-null  object
 7   release_year  16745 non-null  float64
 8   rating        16069 non-null  object
 9   duration      16499 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.5+ MB

In [23]:
df.describe()

       release_year
count  16745.000000
mean    2014.256972
std        8.685029
min     1925.000000
25%     2014.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [6]:
import numpy as np             #New CSV File Amazon      
import pandas as pd
df = pd.read_csv("amazon.csv")
print(df)
print("CSV File Created Successfully")

        user_id product_id     category subcategory    brand     price  \
0       U356787     P39256  Electronics      Mobile      H&M  33090.51
1       U198246     P38657       Sports     Outdoor  Samsung   9368.97
2       U539898     P38893       Sports     Fitness      H&M  14756.85
3       U325772     P54118       Beauty      Makeup     Sony    668.83
4       U865179     P70217         Home       Decor     Sony  10881.29
...         ...        ...          ...         ...      ...       ...
999995  U485987     P55818       Sports     Cycling     Sony   1478.80
999996  U917934     P59467       Sports     Cycling      H&M   4532.12
999997  U667215     P21840  Electronics      Laptop   Lenovo  14986.75
999998  U640883     P46092     Clothing         Men  Samsung   4473.67
999999  U220301     P91830  Electronics      Laptop  Samsung  71369.83

        discount  final_price  rating  review_count  stock seller_id  \
0          10.46     29629.31     4.9            43     71     S2679
1           5.32      8870.73     3.9            13    119     S9279
2          26.00     10919.43     4.2            46    229     S5557
3          24.81       502.91     3.8             6     52     S2519
4          48.63      5589.58     4.0            48    274     S3045
...          ...          ...     ...           ...    ...       ...
999995     36.55       938.34     4.1            15    392     S7795
999996      5.22      4295.44     4.2            32     17     S4919
999997     29.00     10640.50     4.5           115    382     S4196
999998     21.43      3514.86     4.2            14    451     S3812
999999      8.25     65480.69     5.0            36    109     S1286

        seller_rating purchase_date  shipping_time_days   location  \
0                 4.3    2025-03-04                   6  Bangalore
1                 4.9    2025-12-12                   1      Delhi
2                 4.9    2024-04-25                   1    Chennai
3                 3.1    2025-12-18                   2     Mumbai
4                 2.6    2024-05-16                   5      Delhi
...               ...           ...                 ...        ...
999995            4.2    2025-03-12                   1      Delhi
999996            3.6    2025-11-04                   5  Hyderabad
999997            2.8    2025-11-06                   5  Hyderabad
999998            2.9    2025-02-25                   1      Delhi
999999            2.8    2025-05-28                   5    Chennai

            device payment_method  is_returned delivery_status
0           Tablet            UPI         True        Returned
1           Tablet            UPI         True        Returned
2       Mobile App    Credit Card         True        Returned
3              Web            UPI        False      In Transit
4              Web            UPI        False         Delayed
...            ...            ...          ...             ...
999995  Mobile App    Credit Card        False       Delivered
999996  Mobile App     Debit Card        False      In Transit
999997         Web     Debit Card        False      In Transit
999998      Tablet     Debit Card        False       Delivered
999999  Mobile App            UPI        False         Delayed

[1000000 rows x 20 columns]
CSV File Created Successfully

In [7]:
df.head(5)              #Question

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.31,4.9,43,71,S2679,4.3,2025-03-04,6,Bangalore,Tablet,UPI,True,Returned
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.73,3.9,13,119,S9279,4.9,2025-12-12,1,Delhi,Tablet,UPI,True,Returned
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10919.43,4.2,46,229,S5557,4.9,2024-04-25,1,Chennai,Mobile App,Credit Card,True,Returned
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.91,3.8,6,52,S2519,3.1,2025-12-18,2,Mumbai,Web,UPI,False,In Transit
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.58,4.0,48,274,S3045,2.6,2024-05-16,5,Delhi,Web,UPI,False,Delayed

In [8]:
df.tail(5)

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
999995,U485987,P55818,Sports,Cycling,Sony,1478.80,36.55,938.34,4.1,15,392,S7795,4.2,2025-03-12,1,Delhi,Mobile App,Credit Card,False,Delivered
999996,U917934,P59467,Sports,Cycling,H&M,4532.12,5.22,4295.44,4.2,32,17,S4919,3.6,2025-11-04,5,Hyderabad,Mobile App,Debit Card,False,In Transit
999997,U667215,P21840,Electronics,Laptop,Lenovo,14986.75,29.00,10640.50,4.5,115,382,S4196,2.8,2025-11-06,5,Hyderabad,Web,Debit Card,False,In Transit
999998,U640883,P46092,Clothing,Men,Samsung,4473.67,21.43,3514.86,4.2,14,451,S3812,2.9,2025-02-25,1,Delhi,Tablet,Debit Card,False,Delivered
999999,U220301,P91830,Electronics,Laptop,Samsung,71369.83,8.25,65480.69,5.0,36,109,S1286,2.8,2025-05-28,5,Chennai,Mobile App,UPI,False,Delayed

In [9]:
df.sample(5)

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
839030,U664355,P22729,Beauty,Skincare,Zara,2413.01,38.11,1493.45,4.1,39,259,S8205,3.4,2025-04-27,6,Chennai,Web,Debit Card,False,Delayed
59397,U281099,P18361,Clothing,Women,Adidas,4783.80,16.92,3974.37,3.5,3,426,S5861,4.3,2024-09-09,5,Mumbai,Web,Credit Card,False,In Transit
193356,U566596,P35464,Sports,Cycling,Apple,11710.52,5.98,11009.88,4.0,83,331,S8841,2.9,2025-11-15,5,Bangalore,Tablet,Credit Card,False,Delayed
932427,U145285,P72324,Beauty,Makeup,Nike,4424.97,5.67,4174.19,3.3,6,116,S6427,3.2,2024-10-30,1,Delhi,Tablet,UPI,False,In Transit
171401,U346834,P12617,Clothing,Women,LG,3323.46,22.91,2562.15,3.7,7,273,S4738,4.2,2024-04-13,4,Hyderabad,Web,Cash on Delivery,True,Returned

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 20 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   user_id             1000000 non-null  object
 1   product_id          1000000 non-null  object
 2   category            1000000 non-null  object
 3   subcategory         1000000 non-null  object
 4   brand               1000000 non-null  object
 5   price               1000000 non-null  float64
 6   discount            1000000 non-null  float64
 7   final_price         1000000 non-null  float64
 8   rating              1000000 non-null  float64
 9   review_count        1000000 non-null  int64
 10  stock               1000000 non-null  int64
 11  seller_id           1000000 non-null  object
 12  seller_rating       1000000 non-null  float64
 13  purchase_date       1000000 non-null  object
 14  shipping_time_days  1000000 non-null  int64
 15  location            1000000 non-null  object
 16  device              1000000 non-null  object
 17  payment_method      1000000 non-null  object
 18  is_returned         1000000 non-null  bool
 19  delivery_status     1000000 non-null  object
dtypes: bool(1), float64(5), int64(3), object(11)
memory usage: 145.9+ MB

In [13]:
df.columns

Index(['user_id', 'product_id', 'category', 'subcategory', 'brand', 'price',
       'discount', 'final_price', 'rating', 'review_count', 'stock',
       'seller_id', 'seller_rating', 'purchase_date', 'shipping_time_days',
       'location', 'device', 'payment_method', 'is_returned',
       'delivery_status'],
      dtype='object')

In [16]:
df.dtypes

user_id                object
product_id             object
category               object
subcategory            object
brand                  object
price                 float64
discount              float64
final_price           float64
rating                float64
review_count            int64
stock                   int64
seller_id              object
seller_rating         float64
purchase_date          object
shipping_time_days      int64
location               object
device                 object
payment_method         object
is_returned              bool
delivery_status        object
dtype: object

In [17]:
df.info

<bound method DataFrame.info of         user_id product_id     category subcategory    brand     price  \
0       U356787     P39256  Electronics      Mobile      H&M  33090.51
1       U198246     P38657       Sports     Outdoor  Samsung   9368.97
2       U539898     P38893       Sports     Fitness      H&M  14756.85
3       U325772     P54118       Beauty      Makeup     Sony    668.83
4       U865179     P70217         Home       Decor     Sony  10881.29
...         ...        ...          ...         ...      ...       ...
999995  U485987     P55818       Sports     Cycling     Sony   1478.80
999996  U917934     P59467       Sports     Cycling      H&M   4532.12
999997  U667215     P21840  Electronics      Laptop   Lenovo  14986.75
999998  U640883     P46092     Clothing         Men  Samsung   4473.67
999999  U220301     P91830  Electronics      Laptop  Samsung  71369.83

        discount  final_price  rating  review_count  stock seller_id  \
0          10.46     29629.31     4.9            43     71     S2679
1           5.32      8870.73     3.9            13    119     S9279
2          26.00     10919.43     4.2            46    229     S5557
3          24.81       502.91     3.8             6     52     S2519
4          48.63      5589.58     4.0            48    274     S3045
...          ...          ...     ...           ...    ...       ...
999995     36.55       938.34     4.1            15    392     S7795
999996      5.22      4295.44     4.2            32     17     S4919
999997     29.00     10640.50     4.5           115    382     S4196
999998     21.43      3514.86     4.2            14    451     S3812
999999      8.25     65480.69     5.0            36    109     S1286

        seller_rating purchase_date  shipping_time_days   location  \
0                 4.3    2025-03-04                   6  Bangalore
1                 4.9    2025-12-12                   1      Delhi
2                 4.9    2024-04-25                   1    Chennai
3                 3.1    2025-12-18                   2     Mumbai
4                 2.6    2024-05-16                   5      Delhi
...               ...           ...                 ...        ...
999995            4.2    2025-03-12                   1      Delhi
999996            3.6    2025-11-04                   5  Hyderabad
999997            2.8    2025-11-06                   5  Hyderabad
999998            2.9    2025-02-25                   1      Delhi
999999            2.8    2025-05-28                   5    Chennai

            device payment_method  is_returned delivery_status
0           Tablet            UPI         True        Returned
1           Tablet            UPI         True        Returned
2       Mobile App    Credit Card         True        Returned
3              Web            UPI        False      In Transit
4              Web            UPI        False         Delayed
...            ...            ...          ...             ...
999995  Mobile App    Credit Card        False       Delivered
999996  Mobile App     Debit Card        False      In Transit
999997         Web     Debit Card        False      In Transit
999998      Tablet     Debit Card        False       Delivered
999999  Mobile App            UPI        False         Delayed

[1000000 rows x 20 columns]>

In [20]:
df.describe()

,price,discount,final_price,rating,review_count,stock,seller_rating,shipping_time_days
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,13224.119093,28.996161,9938.876985,3.927226,32.626704,250.023345,3.750030,3.166389
std,18079.626921,14.681077,14271.885557,0.519443,43.382201,144.567038,0.722092,1.674178
min,200.030000,5.000000,101.460000,1.500000,0.000000,0.000000,2.500000,1.000000
25%,2700.147500,16.910000,1705.930000,3.600000,10.000000,125.000000,3.100000,2.000000
50%,4971.830000,28.070000,3790.795000,3.900000,20.000000,250.000000,3.800000,3.000000
75%,14134.482500,39.240000,10384.440000,4.300000,39.000000,375.000000,4.400000,5.000000
max,79999.700000,70.000000,75831.110000,5.000000,3408.000000,500.000000,5.000000,6.000000

In [21]:
df.empty

False

In [30]:
df = pd.DataFrame({
    "Product":["TV","AC","Laptop","Remote","Mouse"],
    "Sale":[20000,40000,50000,10000,15000],
    "Quantity":[100,200,500,700,600]
})
print(df)

  Product   Sale  Quantity
0      TV  20000       100
1      AC  40000       200
2  Laptop  50000       500
3  Remote  10000       700
4   Mouse  15000       600

In [31]:
df[df["Sale"]>20000]
print(df[df["Sale"]>20000])

  Product   Sale  Quantity
1      AC  40000       200
2  Laptop  50000       500

In [33]:
df[df["Quantity"]>400]
print(df[df["Quantity"]>400])

  Product   Sale  Quantity
2  Laptop  50000       500
3  Remote  10000       700
4   Mouse  15000       600

In [40]:
df["Quantity"]
print(df["Quantity"])

0    100
1    200
2    500
3    700
4    600
Name: Quantity, dtype: int64

In [42]:
df[df["Product"] == "Laptop"]

  Product   Sale  Quantity
2  Laptop  50000       500

In [61]:
df = pd.DataFrame({
    "Product": ["Laptop", "Notebook", "Book", "Mouse", "Book Stand", "Keyboard"],
    "City": ["Jaipur", "Delhi", "Mumbai", "Jaipur", "Delhi", "Pune"],
    "Sales": [50000, 8000, 8000, 3000, 12000, 15000],
    "Rating": [4.5, 4.0, 4.7, 3.8, 4.5, 4.1],
    "Index":[101,102,103,104,105,106]})


print(df)

      Product    City  Sales  Rating  Index
0      Laptop  Jaipur  50000     4.5    101
1    Notebook   Delhi   8000     4.0    102
2        Book  Mumbai   8000     4.7    103
3       Mouse  Jaipur   3000     3.8    104
4  Book Stand   Delhi  12000     4.5    105
5    Keyboard    Pune  15000     4.1    106

In [48]:
print(df[df["Sales"] > 10000])

      Product    City  Sales  Rating
0      Laptop  Jaipur  50000     4.5
4  Book Stand   Delhi  12000     4.5
5    Keyboard    Pune  15000     4.1

In [49]:
df[df["City"] == "Delhi"]

      Product   City  Sales  Rating
1    Notebook  Delhi   8000     4.0
4  Book Stand  Delhi  12000     4.5

In [53]:
print(df[(df["Sales"] > 10000) & (df["Rating"] > 4.2)])

      Product    City  Sales  Rating
0      Laptop  Jaipur  50000     4.5
4  Book Stand   Delhi  12000     4.5

In [54]:
df.loc[0]

Product    Laptop
City       Jaipur
Sales       50000
Rating        4.5
Name: 0, dtype: object

In [55]:
df.iloc[0]

Product    Laptop
City       Jaipur
Sales       50000
Rating        4.5
Name: 0, dtype: object

In [64]:
import pandas as pd

df = pd.DataFrame({
    "Order_ID": range(1001, 1051),

    "Product": [
        "Laptop", "Mouse", "Keyboard", "Notebook", "Monitor",
        "Book Stand", "Headphones", "Printer", "Tablet", "Pen Drive",
        "Laptop Bag", "Book", "Webcam", "Chair", "Desk",
        "Notebook", "Mouse Pad", "Keyboard", "Laptop", "Monitor",
        "Book Shelf", "Headphones", "Printer", "Tablet", "Pen",
        "Laptop Bag", "Book", "Webcam", "Chair", "Desk",
        "Keyboard", "Mouse", "Laptop", "Notebook", "Monitor",
        "Book Stand", "Printer", "Headphones", "Tablet", "Pen Drive",
        "Laptop", "Book", "Webcam", "Chair", "Desk",
        "Mouse Pad", "Keyboard", "Monitor", "Notebook", "Laptop"
    ],

    "Category": [
        "Electronics", "Accessories", "Accessories", "Books", "Electronics",
        "Books", "Electronics", "Electronics", "Electronics", "Accessories",
        "Accessories", "Books", "Electronics", "Furniture", "Furniture",
        "Books", "Accessories", "Accessories", "Electronics", "Electronics",
        "Books", "Electronics", "Electronics", "Electronics", "Accessories",
        "Accessories", "Books", "Electronics", "Furniture", "Furniture",
        "Accessories", "Accessories", "Electronics", "Books", "Electronics",
        "Books", "Electronics", "Electronics", "Electronics", "Accessories",
        "Electronics", "Books", "Electronics", "Furniture", "Furniture",
        "Accessories", "Accessories", "Electronics", "Books", "Electronics"
    ],

    "City": [
        "Jaipur", "Delhi", "Mumbai", "Pune", "Jaipur",
        "Delhi", "Mumbai", "Kolkata", "Pune", "Jaipur",
        "Delhi", "Mumbai", "Pune", "Jaipur", "Delhi",
        "Kolkata", "Mumbai", "Jaipur", "Delhi", "Pune",
        "Mumbai", "Kolkata", "Jaipur", "Delhi", "Pune",
        "Mumbai", "Jaipur", "Delhi", "Kolkata", "Pune",
        "Jaipur", "Delhi", "Mumbai", "Pune", "Kolkata",
        "Jaipur", "Delhi", "Mumbai", "Pune", "Kolkata",
        "Delhi", "Mumbai", "Jaipur", "Pune", "Kolkata",
        "Jaipur", "Delhi", "Mumbai", "Pune", "Jaipur"
    ],

    "Sales": [
        55000, 2500, 4500, 1800, 32000,
        6500, 8500, 22000, 28000, 4000,
        7500, 3500, 9500, 15000, 12000,
        2500, 1800, 5000, 48000, 27000,
        7000, 9000, 21000, 26000, 1200,
        6500, 3200, 11000, 14500, 13000,
        5200, 2800, 60000, 2200, 30000,
        5500, 19500, 10500, 24000, 3500,
        45000, 4000, 12500, 16000, 14000,
        3000, 4800, 29000, 2000, 68000
    ],

    "Quantity": [
        5, 10, 8, 15, 4,
        6, 7, 3, 5, 9,
        6, 12, 7, 3, 4,
        5, 10, 8, 6, 4,
        7, 6, 3, 5, 15,
        8, 10, 6, 4, 5,
        8, 12, 5, 14, 4,
        9, 3, 5, 7, 10,
        4, 8, 5, 3, 6,
        11, 7, 4, 12, 6
    ],

    "Rating": [
        4.5, 4.0, 3.8, 4.2, 4.7,
        4.1, 4.3, 3.9, 4.6, 3.7,
        4.2, 4.0, 4.4, 4.5, 3.8,
        4.1, 3.9, 4.0, 4.8, 4.5,
        4.2, 4.1, 3.8, 4.6, 3.5,
        4.0, 4.3, 4.5, 3.9, 4.1,
        4.0, 3.8, 4.9, 4.2, 4.7,
        4.1, 3.9, 4.4, 4.6, 3.7,
        4.8, 4.0, 4.3, 4.5, 4.1,
        3.9, 4.2, 4.7, 4.0, 4.9
    ],

    "Payment_Mode": [
        "UPI", "Cash", "Card", "UPI", "Card",
        "Cash", "UPI", "Card", "UPI", "Cash",
        "Card", "UPI", "Cash", "Card", "UPI",
        "Cash", "Card", "UPI", "Card", "Cash",
        "UPI", "Card", "Cash", "UPI", "Card",
        "Cash", "UPI", "Card", "Cash", "UPI",
        "Card", "Cash", "UPI", "Card", "Cash",
        "UPI", "Card", "Cash", "UPI", "Card",
        "Cash", "UPI", "Card", "Cash", "UPI",
        "Card", "Cash", "UPI", "Card", "Cash"
    ]
})

print(df)

    Order_ID     Product     Category     City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics   Jaipur  55000         5     4.5
1       1002       Mouse  Accessories    Delhi   2500        10     4.0
2       1003    Keyboard  Accessories   Mumbai   4500         8     3.8
3       1004    Notebook        Books     Pune   1800        15     4.2
4       1005     Monitor  Electronics   Jaipur  32000         4     4.7
5       1006  Book Stand        Books    Delhi   6500         6     4.1
6       1007  Headphones  Electronics   Mumbai   8500         7     4.3
7       1008     Printer  Electronics  Kolkata  22000         3     3.9
8       1009      Tablet  Electronics     Pune  28000         5     4.6
9       1010   Pen Drive  Accessories   Jaipur   4000         9     3.7
10      1011  Laptop Bag  Accessories    Delhi   7500         6     4.2
11      1012        Book        Books   Mumbai   3500        12     4.0
12      1013      Webcam  Electronics     Pune   9500         7     4.4
13      1014       Chair    Furniture   Jaipur  15000         3     4.5
14      1015        Desk    Furniture    Delhi  12000         4     3.8
15      1016    Notebook        Books  Kolkata   2500         5     4.1
16      1017   Mouse Pad  Accessories   Mumbai   1800        10     3.9
17      1018    Keyboard  Accessories   Jaipur   5000         8     4.0
18      1019      Laptop  Electronics    Delhi  48000         6     4.8
19      1020     Monitor  Electronics     Pune  27000         4     4.5
20      1021  Book Shelf        Books   Mumbai   7000         7     4.2
21      1022  Headphones  Electronics  Kolkata   9000         6     4.1
22      1023     Printer  Electronics   Jaipur  21000         3     3.8
23      1024      Tablet  Electronics    Delhi  26000         5     4.6
24      1025         Pen  Accessories     Pune   1200        15     3.5
25      1026  Laptop Bag  Accessories   Mumbai   6500         8     4.0
26      1027        Book        Books   Jaipur   3200        10     4.3
27      1028      Webcam  Electronics    Delhi  11000         6     4.5
28      1029       Chair    Furniture  Kolkata  14500         4     3.9
29      1030        Desk    Furniture     Pune  13000         5     4.1
30      1031    Keyboard  Accessories   Jaipur   5200         8     4.0
31      1032       Mouse  Accessories    Delhi   2800        12     3.8
32      1033      Laptop  Electronics   Mumbai  60000         5     4.9
33      1034    Notebook        Books     Pune   2200        14     4.2
34      1035     Monitor  Electronics  Kolkata  30000         4     4.7
35      1036  Book Stand        Books   Jaipur   5500         9     4.1
36      1037     Printer  Electronics    Delhi  19500         3     3.9
37      1038  Headphones  Electronics   Mumbai  10500         5     4.4
38      1039      Tablet  Electronics     Pune  24000         7     4.6
39      1040   Pen Drive  Accessories  Kolkata   3500        10     3.7
40      1041      Laptop  Electronics    Delhi  45000         4     4.8
41      1042        Book        Books   Mumbai   4000         8     4.0
42      1043      Webcam  Electronics   Jaipur  12500         5     4.3
43      1044       Chair    Furniture     Pune  16000         3     4.5
44      1045        Desk    Furniture  Kolkata  14000         6     4.1
45      1046   Mouse Pad  Accessories   Jaipur   3000        11     3.9
46      1047    Keyboard  Accessories    Delhi   4800         7     4.2
47      1048     Monitor  Electronics   Mumbai  29000         4     4.7
48      1049    Notebook        Books     Pune   2000        12     4.0
49      1050      Laptop  Electronics   Jaipur  68000         6     4.9

   Payment_Mode
0           UPI
1          Cash
2          Card
3           UPI
4          Card
5          Cash
6           UPI
7          Card
8           UPI
9          Cash
10         Card
11          UPI
12         Cash
13         Card
14          UPI
15         Cash
16         Card
17          UPI
18         Card
19         Cash
20          UPI
21         Card
22         Cash
23          UPI
24         Card
25         Cash
26          UPI
27         Card
28         Cash
29          UPI
30         Card
31         Cash
32          UPI
33         Card
34         Cash
35          UPI
36         Card
37         Cash
38          UPI
39         Card
40         Cash
41          UPI
42         Card
43         Cash
44          UPI
45         Card
46         Cash
47          UPI
48         Card
49         Cash

In [65]:
print(df[df["Sales"] > 10000])       #Question

    Order_ID     Product     Category     City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics   Jaipur  55000         5     4.5
4       1005     Monitor  Electronics   Jaipur  32000         4     4.7
7       1008     Printer  Electronics  Kolkata  22000         3     3.9
8       1009      Tablet  Electronics     Pune  28000         5     4.6
13      1014       Chair    Furniture   Jaipur  15000         3     4.5
14      1015        Desk    Furniture    Delhi  12000         4     3.8
18      1019      Laptop  Electronics    Delhi  48000         6     4.8
19      1020     Monitor  Electronics     Pune  27000         4     4.5
22      1023     Printer  Electronics   Jaipur  21000         3     3.8
23      1024      Tablet  Electronics    Delhi  26000         5     4.6
27      1028      Webcam  Electronics    Delhi  11000         6     4.5
28      1029       Chair    Furniture  Kolkata  14500         4     3.9
29      1030        Desk    Furniture     Pune  13000         5     4.1
32      1033      Laptop  Electronics   Mumbai  60000         5     4.9
34      1035     Monitor  Electronics  Kolkata  30000         4     4.7
36      1037     Printer  Electronics    Delhi  19500         3     3.9
37      1038  Headphones  Electronics   Mumbai  10500         5     4.4
38      1039      Tablet  Electronics     Pune  24000         7     4.6
40      1041      Laptop  Electronics    Delhi  45000         4     4.8
42      1043      Webcam  Electronics   Jaipur  12500         5     4.3
43      1044       Chair    Furniture     Pune  16000         3     4.5
44      1045        Desk    Furniture  Kolkata  14000         6     4.1
47      1048     Monitor  Electronics   Mumbai  29000         4     4.7
49      1050      Laptop  Electronics   Jaipur  68000         6     4.9

   Payment_Mode
0           UPI
4          Card
7          Card
8           UPI
13         Card
14          UPI
18         Card
19         Cash
22         Cash
23          UPI
27         Card
28         Cash
29          UPI
32          UPI
34         Cash
36         Card
37         Cash
38          UPI
40         Cash
42         Card
43         Cash
44          UPI
47          UPI
49         Cash

In [66]:
df[df["City"] == "Jaipur"]

,Order_ID,Product,Category,City,Sales,Quantity,Rating,Payment_Mode
0,1001,Laptop,Electronics,Jaipur,55000,5,4.5,UPI
4,1005,Monitor,Electronics,Jaipur,32000,4,4.7,Card
9,1010,Pen Drive,Accessories,Jaipur,4000,9,3.7,Cash
13,1014,Chair,Furniture,Jaipur,15000,3,4.5,Card
17,1018,Keyboard,Accessories,Jaipur,5000,8,4.0,UPI
22,1023,Printer,Electronics,Jaipur,21000,3,3.8,Cash
26,1027,Book,Books,Jaipur,3200,10,4.3,UPI
30,1031,Keyboard,Accessories,Jaipur,5200,8,4.0,Card
35,1036,Book Stand,Books,Jaipur,5500,9,4.1,UPI
42,1043,Webcam,Electronics,Jaipur,12500,5,4.3,Card
45,1046,Mouse Pad,Accessories,Jaipur,3000,11,3.9,Card
49,1050,Laptop,Electronics,Jaipur,68000,6,4.9,Cash

In [75]:
df[df["Rating"] >= 4.5]

,Order_ID,Product,Category,City,Sales,Quantity,Rating,Payment_Mode
0,1001,Laptop,Electronics,Jaipur,55000,5,4.5,UPI
4,1005,Monitor,Electronics,Jaipur,32000,4,4.7,Card
8,1009,Tablet,Electronics,Pune,28000,5,4.6,UPI
13,1014,Chair,Furniture,Jaipur,15000,3,4.5,Card
18,1019,Laptop,Electronics,Delhi,48000,6,4.8,Card
19,1020,Monitor,Electronics,Pune,27000,4,4.5,Cash
23,1024,Tablet,Electronics,Delhi,26000,5,4.6,UPI
27,1028,Webcam,Electronics,Delhi,11000,6,4.5,Card
32,1033,Laptop,Electronics,Mumbai,60000,5,4.9,UPI
34,1035,Monitor,Electronics,Kolkata,30000,4,4.7,Cash
38,1039,Tablet,Electronics,Pune,24000,7,4.6,UPI
40,1041,Laptop,Electronics,Delhi,45000,4,4.8,Cash
43,1044,Chair,Furniture,Pune,16000,3,4.5,Cash
47,1048,Monitor,Electronics,Mumbai,29000,4,4.7,UPI
49,1050,Laptop,Electronics,Jaipur,68000,6,4.9,Cash

In [70]:
df[df["Category"] == "Electronics"]

,Order_ID,Product,Category,City,Sales,Quantity,Rating,Payment_Mode
0,1001,Laptop,Electronics,Jaipur,55000,5,4.5,UPI
4,1005,Monitor,Electronics,Jaipur,32000,4,4.7,Card
6,1007,Headphones,Electronics,Mumbai,8500,7,4.3,UPI
7,1008,Printer,Electronics,Kolkata,22000,3,3.9,Card
8,1009,Tablet,Electronics,Pune,28000,5,4.6,UPI
12,1013,Webcam,Electronics,Pune,9500,7,4.4,Cash
18,1019,Laptop,Electronics,Delhi,48000,6,4.8,Card
19,1020,Monitor,Electronics,Pune,27000,4,4.5,Cash
21,1022,Headphones,Electronics,Kolkata,9000,6,4.1,Card
22,1023,Printer,Electronics,Jaipur,21000,3,3.8,Cash
23,1024,Tablet,Electronics,Delhi,26000,5,4.6,UPI
27,1028,Webcam,Electronics,Delhi,11000,6,4.5,Card
32,1033,Laptop,Electronics,Mumbai,60000,5,4.9,UPI
34,1035,Monitor,Electronics,Kolkata,30000,4,4.7,Cash
36,1037,Printer,Electronics,Delhi,19500,3,3.9,Card
37,1038,Headphones,Electronics,Mumbai,10500,5,4.4,Cash
38,1039,Tablet,Electronics,Pune,24000,7,4.6,UPI
40,1041,Laptop,Electronics,Delhi,45000,4,4.8,Cash
42,1043,Webcam,Electronics,Jaipur,12500,5,4.3,Card
47,1048,Monitor,Electronics,Mumbai,29000,4,4.7,UPI
49,1050,Laptop,Electronics,Jaipur,68000,6,4.9,Cash

In [71]:
print(df[(df["Sales"] > 10000) & (df["Rating"] > 4.0)])

    Order_ID     Product     Category     City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics   Jaipur  55000         5     4.5
4       1005     Monitor  Electronics   Jaipur  32000         4     4.7
8       1009      Tablet  Electronics     Pune  28000         5     4.6
13      1014       Chair    Furniture   Jaipur  15000         3     4.5
18      1019      Laptop  Electronics    Delhi  48000         6     4.8
19      1020     Monitor  Electronics     Pune  27000         4     4.5
23      1024      Tablet  Electronics    Delhi  26000         5     4.6
27      1028      Webcam  Electronics    Delhi  11000         6     4.5
29      1030        Desk    Furniture     Pune  13000         5     4.1
32      1033      Laptop  Electronics   Mumbai  60000         5     4.9
34      1035     Monitor  Electronics  Kolkata  30000         4     4.7
37      1038  Headphones  Electronics   Mumbai  10500         5     4.4
38      1039      Tablet  Electronics     Pune  24000         7     4.6
40      1041      Laptop  Electronics    Delhi  45000         4     4.8
42      1043      Webcam  Electronics   Jaipur  12500         5     4.3
43      1044       Chair    Furniture     Pune  16000         3     4.5
44      1045        Desk    Furniture  Kolkata  14000         6     4.1
47      1048     Monitor  Electronics   Mumbai  29000         4     4.7
49      1050      Laptop  Electronics   Jaipur  68000         6     4.9

   Payment_Mode
0           UPI
4          Card
8           UPI
13         Card
18         Card
19         Cash
23          UPI
27         Card
29          UPI
32          UPI
34         Cash
37         Cash
38          UPI
40         Cash
42         Card
43         Cash
44          UPI
47          UPI
49         Cash

In [73]:
print(df[(df["Sales"] > 20000) & (df["Quantity"] > 5)])

    Order_ID Product     Category    City  Sales  Quantity  Rating  \
18      1019  Laptop  Electronics   Delhi  48000         6     4.8
38      1039  Tablet  Electronics    Pune  24000         7     4.6
49      1050  Laptop  Electronics  Jaipur  68000         6     4.9

   Payment_Mode
18         Card
38          UPI
49         Cash

In [76]:
print(df[(df["Category"] == "Electronics") & (df["Sales"] > 15000)])

    Order_ID  Product     Category     City  Sales  Quantity  Rating  \
0       1001   Laptop  Electronics   Jaipur  55000         5     4.5
4       1005  Monitor  Electronics   Jaipur  32000         4     4.7
7       1008  Printer  Electronics  Kolkata  22000         3     3.9
8       1009   Tablet  Electronics     Pune  28000         5     4.6
18      1019   Laptop  Electronics    Delhi  48000         6     4.8
19      1020  Monitor  Electronics     Pune  27000         4     4.5
22      1023  Printer  Electronics   Jaipur  21000         3     3.8
23      1024   Tablet  Electronics    Delhi  26000         5     4.6
32      1033   Laptop  Electronics   Mumbai  60000         5     4.9
34      1035  Monitor  Electronics  Kolkata  30000         4     4.7
36      1037  Printer  Electronics    Delhi  19500         3     3.9
38      1039   Tablet  Electronics     Pune  24000         7     4.6
40      1041   Laptop  Electronics    Delhi  45000         4     4.8
47      1048  Monitor  Electronics   Mumbai  29000         4     4.7
49      1050   Laptop  Electronics   Jaipur  68000         6     4.9

   Payment_Mode
0           UPI
4          Card
7          Card
8           UPI
18         Card
19         Cash
22         Cash
23          UPI
32          UPI
34         Cash
36         Card
38          UPI
40         Cash
47          UPI
49         Cash

In [77]:
print(df[(df["City"] == "Jaipur") & (df["Rating"] >= 4.5)])

    Order_ID  Product     Category    City  Sales  Quantity  Rating  \
0       1001   Laptop  Electronics  Jaipur  55000         5     4.5
4       1005  Monitor  Electronics  Jaipur  32000         4     4.7
13      1014    Chair    Furniture  Jaipur  15000         3     4.5
49      1050   Laptop  Electronics  Jaipur  68000         6     4.9

   Payment_Mode
0           UPI
4          Card
13         Card
49         Cash

In [78]:
print(df[(df["City"]=="Jaipur") & (df["Rating"]>=4.0)])

    Order_ID     Product     Category    City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics  Jaipur  55000         5     4.5
4       1005     Monitor  Electronics  Jaipur  32000         4     4.7
13      1014       Chair    Furniture  Jaipur  15000         3     4.5
17      1018    Keyboard  Accessories  Jaipur   5000         8     4.0
26      1027        Book        Books  Jaipur   3200        10     4.3
30      1031    Keyboard  Accessories  Jaipur   5200         8     4.0
35      1036  Book Stand        Books  Jaipur   5500         9     4.1
42      1043      Webcam  Electronics  Jaipur  12500         5     4.3
49      1050      Laptop  Electronics  Jaipur  68000         6     4.9

   Payment_Mode
0           UPI
4          Card
13         Card
17          UPI
26          UPI
30         Card
35          UPI
42         Card
49         Cash

In [80]:
print(df[(df["Category"]=="Electronics") |(df["Category"]=="Books")])

    Order_ID     Product     Category     City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics   Jaipur  55000         5     4.5
3       1004    Notebook        Books     Pune   1800        15     4.2
4       1005     Monitor  Electronics   Jaipur  32000         4     4.7
5       1006  Book Stand        Books    Delhi   6500         6     4.1
6       1007  Headphones  Electronics   Mumbai   8500         7     4.3
7       1008     Printer  Electronics  Kolkata  22000         3     3.9
8       1009      Tablet  Electronics     Pune  28000         5     4.6
11      1012        Book        Books   Mumbai   3500        12     4.0
12      1013      Webcam  Electronics     Pune   9500         7     4.4
15      1016    Notebook        Books  Kolkata   2500         5     4.1
18      1019      Laptop  Electronics    Delhi  48000         6     4.8
19      1020     Monitor  Electronics     Pune  27000         4     4.5
20      1021  Book Shelf        Books   Mumbai   7000         7     4.2
21      1022  Headphones  Electronics  Kolkata   9000         6     4.1
22      1023     Printer  Electronics   Jaipur  21000         3     3.8
23      1024      Tablet  Electronics    Delhi  26000         5     4.6
26      1027        Book        Books   Jaipur   3200        10     4.3
27      1028      Webcam  Electronics    Delhi  11000         6     4.5
32      1033      Laptop  Electronics   Mumbai  60000         5     4.9
33      1034    Notebook        Books     Pune   2200        14     4.2
34      1035     Monitor  Electronics  Kolkata  30000         4     4.7
35      1036  Book Stand        Books   Jaipur   5500         9     4.1
36      1037     Printer  Electronics    Delhi  19500         3     3.9
37      1038  Headphones  Electronics   Mumbai  10500         5     4.4
38      1039      Tablet  Electronics     Pune  24000         7     4.6
40      1041      Laptop  Electronics    Delhi  45000         4     4.8
41      1042        Book        Books   Mumbai   4000         8     4.0
42      1043      Webcam  Electronics   Jaipur  12500         5     4.3
47      1048     Monitor  Electronics   Mumbai  29000         4     4.7
48      1049    Notebook        Books     Pune   2000        12     4.0
49      1050      Laptop  Electronics   Jaipur  68000         6     4.9

   Payment_Mode
0           UPI
3           UPI
4          Card
5          Cash
6           UPI
7          Card
8           UPI
11          UPI
12         Cash
15         Cash
18         Card
19         Cash
20          UPI
21         Card
22         Cash
23          UPI
26          UPI
27         Card
32          UPI
33         Card
34         Cash
35          UPI
36         Card
37         Cash
38          UPI
40         Cash
41          UPI
42         Card
47          UPI
48         Card
49         Cash

In [84]:
print(df[(df["City"]=="Jaipur")| (df["City"]=="Delhi")])

    Order_ID     Product     Category    City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics  Jaipur  55000         5     4.5
1       1002       Mouse  Accessories   Delhi   2500        10     4.0
4       1005     Monitor  Electronics  Jaipur  32000         4     4.7
5       1006  Book Stand        Books   Delhi   6500         6     4.1
9       1010   Pen Drive  Accessories  Jaipur   4000         9     3.7
10      1011  Laptop Bag  Accessories   Delhi   7500         6     4.2
13      1014       Chair    Furniture  Jaipur  15000         3     4.5
14      1015        Desk    Furniture   Delhi  12000         4     3.8
17      1018    Keyboard  Accessories  Jaipur   5000         8     4.0
18      1019      Laptop  Electronics   Delhi  48000         6     4.8
22      1023     Printer  Electronics  Jaipur  21000         3     3.8
23      1024      Tablet  Electronics   Delhi  26000         5     4.6
26      1027        Book        Books  Jaipur   3200        10     4.3
27      1028      Webcam  Electronics   Delhi  11000         6     4.5
30      1031    Keyboard  Accessories  Jaipur   5200         8     4.0
31      1032       Mouse  Accessories   Delhi   2800        12     3.8
35      1036  Book Stand        Books  Jaipur   5500         9     4.1
36      1037     Printer  Electronics   Delhi  19500         3     3.9
40      1041      Laptop  Electronics   Delhi  45000         4     4.8
42      1043      Webcam  Electronics  Jaipur  12500         5     4.3
45      1046   Mouse Pad  Accessories  Jaipur   3000        11     3.9
46      1047    Keyboard  Accessories   Delhi   4800         7     4.2
49      1050      Laptop  Electronics  Jaipur  68000         6     4.9

   Payment_Mode
0           UPI
1          Cash
4          Card
5          Cash
9          Cash
10         Card
13         Card
14          UPI
17          UPI
18         Card
22         Cash
23          UPI
26          UPI
27         Card
30         Card
31         Cash
35          UPI
36         Card
40         Cash
42         Card
45         Card
46         Cash
49         Cash

In [85]:
print(df[(df["Payment_Mode"]=="UPI") | (df["Payment_Mode"]=="Card")])

    Order_ID     Product     Category     City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics   Jaipur  55000         5     4.5
2       1003    Keyboard  Accessories   Mumbai   4500         8     3.8
3       1004    Notebook        Books     Pune   1800        15     4.2
4       1005     Monitor  Electronics   Jaipur  32000         4     4.7
6       1007  Headphones  Electronics   Mumbai   8500         7     4.3
7       1008     Printer  Electronics  Kolkata  22000         3     3.9
8       1009      Tablet  Electronics     Pune  28000         5     4.6
10      1011  Laptop Bag  Accessories    Delhi   7500         6     4.2
11      1012        Book        Books   Mumbai   3500        12     4.0
13      1014       Chair    Furniture   Jaipur  15000         3     4.5
14      1015        Desk    Furniture    Delhi  12000         4     3.8
16      1017   Mouse Pad  Accessories   Mumbai   1800        10     3.9
17      1018    Keyboard  Accessories   Jaipur   5000         8     4.0
18      1019      Laptop  Electronics    Delhi  48000         6     4.8
20      1021  Book Shelf        Books   Mumbai   7000         7     4.2
21      1022  Headphones  Electronics  Kolkata   9000         6     4.1
23      1024      Tablet  Electronics    Delhi  26000         5     4.6
24      1025         Pen  Accessories     Pune   1200        15     3.5
26      1027        Book        Books   Jaipur   3200        10     4.3
27      1028      Webcam  Electronics    Delhi  11000         6     4.5
29      1030        Desk    Furniture     Pune  13000         5     4.1
30      1031    Keyboard  Accessories   Jaipur   5200         8     4.0
32      1033      Laptop  Electronics   Mumbai  60000         5     4.9
33      1034    Notebook        Books     Pune   2200        14     4.2
35      1036  Book Stand        Books   Jaipur   5500         9     4.1
36      1037     Printer  Electronics    Delhi  19500         3     3.9
38      1039      Tablet  Electronics     Pune  24000         7     4.6
39      1040   Pen Drive  Accessories  Kolkata   3500        10     3.7
41      1042        Book        Books   Mumbai   4000         8     4.0
42      1043      Webcam  Electronics   Jaipur  12500         5     4.3
44      1045        Desk    Furniture  Kolkata  14000         6     4.1
45      1046   Mouse Pad  Accessories   Jaipur   3000        11     3.9
47      1048     Monitor  Electronics   Mumbai  29000         4     4.7
48      1049    Notebook        Books     Pune   2000        12     4.0

   Payment_Mode
0           UPI
2          Card
3           UPI
4          Card
6           UPI
7          Card
8           UPI
10         Card
11          UPI
13         Card
14          UPI
16         Card
17          UPI
18         Card
20          UPI
21         Card
23          UPI
24         Card
26          UPI
27         Card
29          UPI
30         Card
32          UPI
33         Card
35          UPI
36         Card
38          UPI
39         Card
41          UPI
42         Card
44          UPI
45         Card
47          UPI
48         Card

In [87]:
print(df[(df["Category"]=="Books") | (df["Category"]=="Furniture")])

    Order_ID     Product   Category     City  Sales  Quantity  Rating  \
3       1004    Notebook      Books     Pune   1800        15     4.2
5       1006  Book Stand      Books    Delhi   6500         6     4.1
11      1012        Book      Books   Mumbai   3500        12     4.0
13      1014       Chair  Furniture   Jaipur  15000         3     4.5
14      1015        Desk  Furniture    Delhi  12000         4     3.8
15      1016    Notebook      Books  Kolkata   2500         5     4.1
20      1021  Book Shelf      Books   Mumbai   7000         7     4.2
26      1027        Book      Books   Jaipur   3200        10     4.3
28      1029       Chair  Furniture  Kolkata  14500         4     3.9
29      1030        Desk  Furniture     Pune  13000         5     4.1
33      1034    Notebook      Books     Pune   2200        14     4.2
35      1036  Book Stand      Books   Jaipur   5500         9     4.1
41      1042        Book      Books   Mumbai   4000         8     4.0
43      1044       Chair  Furniture     Pune  16000         3     4.5
44      1045        Desk  Furniture  Kolkata  14000         6     4.1
48      1049    Notebook      Books     Pune   2000        12     4.0

   Payment_Mode
3           UPI
5          Cash
11          UPI
13         Card
14          UPI
15         Cash
20          UPI
26          UPI
28         Cash
29          UPI
33         Card
35          UPI
41          UPI
43         Cash
44          UPI
48         Card

In [91]:
print(df[(df["City"]=="Jaipur") | (df["City"]=="Delhi")])

    Order_ID     Product     Category    City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics  Jaipur  55000         5     4.5
1       1002       Mouse  Accessories   Delhi   2500        10     4.0
4       1005     Monitor  Electronics  Jaipur  32000         4     4.7
5       1006  Book Stand        Books   Delhi   6500         6     4.1
9       1010   Pen Drive  Accessories  Jaipur   4000         9     3.7
10      1011  Laptop Bag  Accessories   Delhi   7500         6     4.2
13      1014       Chair    Furniture  Jaipur  15000         3     4.5
14      1015        Desk    Furniture   Delhi  12000         4     3.8
17      1018    Keyboard  Accessories  Jaipur   5000         8     4.0
18      1019      Laptop  Electronics   Delhi  48000         6     4.8
22      1023     Printer  Electronics  Jaipur  21000         3     3.8
23      1024      Tablet  Electronics   Delhi  26000         5     4.6
26      1027        Book        Books  Jaipur   3200        10     4.3
27      1028      Webcam  Electronics   Delhi  11000         6     4.5
30      1031    Keyboard  Accessories  Jaipur   5200         8     4.0
31      1032       Mouse  Accessories   Delhi   2800        12     3.8
35      1036  Book Stand        Books  Jaipur   5500         9     4.1
36      1037     Printer  Electronics   Delhi  19500         3     3.9
40      1041      Laptop  Electronics   Delhi  45000         4     4.8
42      1043      Webcam  Electronics  Jaipur  12500         5     4.3
45      1046   Mouse Pad  Accessories  Jaipur   3000        11     3.9
46      1047    Keyboard  Accessories   Delhi   4800         7     4.2
49      1050      Laptop  Electronics  Jaipur  68000         6     4.9

   Payment_Mode
0           UPI
1          Cash
4          Card
5          Cash
9          Cash
10         Card
13         Card
14          UPI
17          UPI
18         Card
22         Cash
23          UPI
26          UPI
27         Card
30         Card
31         Cash
35          UPI
36         Card
40         Cash
42         Card
45         Card
46         Cash
49         Cash

In [92]:
print(df[df["Payment_Mode"].isin(["UPI", "Card"])])

    Order_ID     Product     Category     City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics   Jaipur  55000         5     4.5
2       1003    Keyboard  Accessories   Mumbai   4500         8     3.8
3       1004    Notebook        Books     Pune   1800        15     4.2
4       1005     Monitor  Electronics   Jaipur  32000         4     4.7
6       1007  Headphones  Electronics   Mumbai   8500         7     4.3
7       1008     Printer  Electronics  Kolkata  22000         3     3.9
8       1009      Tablet  Electronics     Pune  28000         5     4.6
10      1011  Laptop Bag  Accessories    Delhi   7500         6     4.2
11      1012        Book        Books   Mumbai   3500        12     4.0
13      1014       Chair    Furniture   Jaipur  15000         3     4.5
14      1015        Desk    Furniture    Delhi  12000         4     3.8
16      1017   Mouse Pad  Accessories   Mumbai   1800        10     3.9
17      1018    Keyboard  Accessories   Jaipur   5000         8     4.0
18      1019      Laptop  Electronics    Delhi  48000         6     4.8
20      1021  Book Shelf        Books   Mumbai   7000         7     4.2
21      1022  Headphones  Electronics  Kolkata   9000         6     4.1
23      1024      Tablet  Electronics    Delhi  26000         5     4.6
24      1025         Pen  Accessories     Pune   1200        15     3.5
26      1027        Book        Books   Jaipur   3200        10     4.3
27      1028      Webcam  Electronics    Delhi  11000         6     4.5
29      1030        Desk    Furniture     Pune  13000         5     4.1
30      1031    Keyboard  Accessories   Jaipur   5200         8     4.0
32      1033      Laptop  Electronics   Mumbai  60000         5     4.9
33      1034    Notebook        Books     Pune   2200        14     4.2
35      1036  Book Stand        Books   Jaipur   5500         9     4.1
36      1037     Printer  Electronics    Delhi  19500         3     3.9
38      1039      Tablet  Electronics     Pune  24000         7     4.6
39      1040   Pen Drive  Accessories  Kolkata   3500        10     3.7
41      1042        Book        Books   Mumbai   4000         8     4.0
42      1043      Webcam  Electronics   Jaipur  12500         5     4.3
44      1045        Desk    Furniture  Kolkata  14000         6     4.1
45      1046   Mouse Pad  Accessories   Jaipur   3000        11     3.9
47      1048     Monitor  Electronics   Mumbai  29000         4     4.7
48      1049    Notebook        Books     Pune   2000        12     4.0

   Payment_Mode
0           UPI
2          Card
3           UPI
4          Card
6           UPI
7          Card
8           UPI
10         Card
11          UPI
13         Card
14          UPI
16         Card
17          UPI
18         Card
20          UPI
21         Card
23          UPI
24         Card
26          UPI
27         Card
29          UPI
30         Card
32          UPI
33         Card
35          UPI
36         Card
38          UPI
39         Card
41          UPI
42         Card
44          UPI
45         Card
47          UPI
48         Card

In [98]:
print(df[(df["City"]) .isin (["Pune","Kolkata","Jaipur"])])

    Order_ID     Product     Category     City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics   Jaipur  55000         5     4.5
3       1004    Notebook        Books     Pune   1800        15     4.2
4       1005     Monitor  Electronics   Jaipur  32000         4     4.7
7       1008     Printer  Electronics  Kolkata  22000         3     3.9
8       1009      Tablet  Electronics     Pune  28000         5     4.6
9       1010   Pen Drive  Accessories   Jaipur   4000         9     3.7
12      1013      Webcam  Electronics     Pune   9500         7     4.4
13      1014       Chair    Furniture   Jaipur  15000         3     4.5
15      1016    Notebook        Books  Kolkata   2500         5     4.1
17      1018    Keyboard  Accessories   Jaipur   5000         8     4.0
19      1020     Monitor  Electronics     Pune  27000         4     4.5
21      1022  Headphones  Electronics  Kolkata   9000         6     4.1
22      1023     Printer  Electronics   Jaipur  21000         3     3.8
24      1025         Pen  Accessories     Pune   1200        15     3.5
26      1027        Book        Books   Jaipur   3200        10     4.3
28      1029       Chair    Furniture  Kolkata  14500         4     3.9
29      1030        Desk    Furniture     Pune  13000         5     4.1
30      1031    Keyboard  Accessories   Jaipur   5200         8     4.0
33      1034    Notebook        Books     Pune   2200        14     4.2
34      1035     Monitor  Electronics  Kolkata  30000         4     4.7
35      1036  Book Stand        Books   Jaipur   5500         9     4.1
38      1039      Tablet  Electronics     Pune  24000         7     4.6
39      1040   Pen Drive  Accessories  Kolkata   3500        10     3.7
42      1043      Webcam  Electronics   Jaipur  12500         5     4.3
43      1044       Chair    Furniture     Pune  16000         3     4.5
44      1045        Desk    Furniture  Kolkata  14000         6     4.1
45      1046   Mouse Pad  Accessories   Jaipur   3000        11     3.9
48      1049    Notebook        Books     Pune   2000        12     4.0
49      1050      Laptop  Electronics   Jaipur  68000         6     4.9

   Payment_Mode
0           UPI
3           UPI
4          Card
7          Card
8           UPI
9          Cash
12         Cash
13         Card
15         Cash
17          UPI
19         Cash
21         Card
22         Cash
24         Card
26          UPI
28         Cash
29          UPI
30         Card
33         Card
34         Cash
35          UPI
38          UPI
39         Card
42         Card
43         Cash
44          UPI
45         Card
48         Card
49         Cash

In [100]:
print(df[(df["Category"]) .isin(["Electronics","Books","Accessories"])])

    Order_ID     Product     Category     City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics   Jaipur  55000         5     4.5
1       1002       Mouse  Accessories    Delhi   2500        10     4.0
2       1003    Keyboard  Accessories   Mumbai   4500         8     3.8
3       1004    Notebook        Books     Pune   1800        15     4.2
4       1005     Monitor  Electronics   Jaipur  32000         4     4.7
5       1006  Book Stand        Books    Delhi   6500         6     4.1
6       1007  Headphones  Electronics   Mumbai   8500         7     4.3
7       1008     Printer  Electronics  Kolkata  22000         3     3.9
8       1009      Tablet  Electronics     Pune  28000         5     4.6
9       1010   Pen Drive  Accessories   Jaipur   4000         9     3.7
10      1011  Laptop Bag  Accessories    Delhi   7500         6     4.2
11      1012        Book        Books   Mumbai   3500        12     4.0
12      1013      Webcam  Electronics     Pune   9500         7     4.4
15      1016    Notebook        Books  Kolkata   2500         5     4.1
16      1017   Mouse Pad  Accessories   Mumbai   1800        10     3.9
17      1018    Keyboard  Accessories   Jaipur   5000         8     4.0
18      1019      Laptop  Electronics    Delhi  48000         6     4.8
19      1020     Monitor  Electronics     Pune  27000         4     4.5
20      1021  Book Shelf        Books   Mumbai   7000         7     4.2
21      1022  Headphones  Electronics  Kolkata   9000         6     4.1
22      1023     Printer  Electronics   Jaipur  21000         3     3.8
23      1024      Tablet  Electronics    Delhi  26000         5     4.6
24      1025         Pen  Accessories     Pune   1200        15     3.5
25      1026  Laptop Bag  Accessories   Mumbai   6500         8     4.0
26      1027        Book        Books   Jaipur   3200        10     4.3
27      1028      Webcam  Electronics    Delhi  11000         6     4.5
30      1031    Keyboard  Accessories   Jaipur   5200         8     4.0
31      1032       Mouse  Accessories    Delhi   2800        12     3.8
32      1033      Laptop  Electronics   Mumbai  60000         5     4.9
33      1034    Notebook        Books     Pune   2200        14     4.2
34      1035     Monitor  Electronics  Kolkata  30000         4     4.7
35      1036  Book Stand        Books   Jaipur   5500         9     4.1
36      1037     Printer  Electronics    Delhi  19500         3     3.9
37      1038  Headphones  Electronics   Mumbai  10500         5     4.4
38      1039      Tablet  Electronics     Pune  24000         7     4.6
39      1040   Pen Drive  Accessories  Kolkata   3500        10     3.7
40      1041      Laptop  Electronics    Delhi  45000         4     4.8
41      1042        Book        Books   Mumbai   4000         8     4.0
42      1043      Webcam  Electronics   Jaipur  12500         5     4.3
45      1046   Mouse Pad  Accessories   Jaipur   3000        11     3.9
46      1047    Keyboard  Accessories    Delhi   4800         7     4.2
47      1048     Monitor  Electronics   Mumbai  29000         4     4.7
48      1049    Notebook        Books     Pune   2000        12     4.0
49      1050      Laptop  Electronics   Jaipur  68000         6     4.9

   Payment_Mode
0           UPI
1          Cash
2          Card
3           UPI
4          Card
5          Cash
6           UPI
7          Card
8           UPI
9          Cash
10         Card
11          UPI
12         Cash
15         Cash
16         Card
17          UPI
18         Card
19         Cash
20          UPI
21         Card
22         Cash
23          UPI
24         Card
25         Cash
26          UPI
27         Card
30         Card
31         Cash
32          UPI
33         Card
34         Cash
35          UPI
36         Card
37         Cash
38          UPI
39         Card
40         Cash
41          UPI
42         Card
45         Card
46         Cash
47          UPI
48         Card
49         Cash

In [103]:
print(df[df["Sales"] .between(5000,20000)])

    Order_ID     Product     Category     City  Sales  Quantity  Rating  \
5       1006  Book Stand        Books    Delhi   6500         6     4.1
6       1007  Headphones  Electronics   Mumbai   8500         7     4.3
10      1011  Laptop Bag  Accessories    Delhi   7500         6     4.2
12      1013      Webcam  Electronics     Pune   9500         7     4.4
13      1014       Chair    Furniture   Jaipur  15000         3     4.5
14      1015        Desk    Furniture    Delhi  12000         4     3.8
17      1018    Keyboard  Accessories   Jaipur   5000         8     4.0
20      1021  Book Shelf        Books   Mumbai   7000         7     4.2
21      1022  Headphones  Electronics  Kolkata   9000         6     4.1
25      1026  Laptop Bag  Accessories   Mumbai   6500         8     4.0
27      1028      Webcam  Electronics    Delhi  11000         6     4.5
28      1029       Chair    Furniture  Kolkata  14500         4     3.9
29      1030        Desk    Furniture     Pune  13000         5     4.1
30      1031    Keyboard  Accessories   Jaipur   5200         8     4.0
35      1036  Book Stand        Books   Jaipur   5500         9     4.1
36      1037     Printer  Electronics    Delhi  19500         3     3.9
37      1038  Headphones  Electronics   Mumbai  10500         5     4.4
42      1043      Webcam  Electronics   Jaipur  12500         5     4.3
43      1044       Chair    Furniture     Pune  16000         3     4.5
44      1045        Desk    Furniture  Kolkata  14000         6     4.1

   Payment_Mode
5          Cash
6           UPI
10         Card
12         Cash
13         Card
14          UPI
17          UPI
20          UPI
21         Card
25         Cash
27         Card
28         Cash
29          UPI
30         Card
35          UPI
36         Card
37         Cash
42         Card
43         Cash
44          UPI

In [106]:
print(df[df["Quantity"] .between(5,10)])

    Order_ID     Product     Category     City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics   Jaipur  55000         5     4.5
1       1002       Mouse  Accessories    Delhi   2500        10     4.0
2       1003    Keyboard  Accessories   Mumbai   4500         8     3.8
5       1006  Book Stand        Books    Delhi   6500         6     4.1
6       1007  Headphones  Electronics   Mumbai   8500         7     4.3
8       1009      Tablet  Electronics     Pune  28000         5     4.6
9       1010   Pen Drive  Accessories   Jaipur   4000         9     3.7
10      1011  Laptop Bag  Accessories    Delhi   7500         6     4.2
12      1013      Webcam  Electronics     Pune   9500         7     4.4
15      1016    Notebook        Books  Kolkata   2500         5     4.1
16      1017   Mouse Pad  Accessories   Mumbai   1800        10     3.9
17      1018    Keyboard  Accessories   Jaipur   5000         8     4.0
18      1019      Laptop  Electronics    Delhi  48000         6     4.8
20      1021  Book Shelf        Books   Mumbai   7000         7     4.2
21      1022  Headphones  Electronics  Kolkata   9000         6     4.1
23      1024      Tablet  Electronics    Delhi  26000         5     4.6
25      1026  Laptop Bag  Accessories   Mumbai   6500         8     4.0
26      1027        Book        Books   Jaipur   3200        10     4.3
27      1028      Webcam  Electronics    Delhi  11000         6     4.5
29      1030        Desk    Furniture     Pune  13000         5     4.1
30      1031    Keyboard  Accessories   Jaipur   5200         8     4.0
32      1033      Laptop  Electronics   Mumbai  60000         5     4.9
35      1036  Book Stand        Books   Jaipur   5500         9     4.1
37      1038  Headphones  Electronics   Mumbai  10500         5     4.4
38      1039      Tablet  Electronics     Pune  24000         7     4.6
39      1040   Pen Drive  Accessories  Kolkata   3500        10     3.7
41      1042        Book        Books   Mumbai   4000         8     4.0
42      1043      Webcam  Electronics   Jaipur  12500         5     4.3
44      1045        Desk    Furniture  Kolkata  14000         6     4.1
46      1047    Keyboard  Accessories    Delhi   4800         7     4.2
49      1050      Laptop  Electronics   Jaipur  68000         6     4.9

   Payment_Mode
0           UPI
1          Cash
2          Card
5          Cash
6           UPI
8           UPI
9          Cash
10         Card
12         Cash
15         Cash
16         Card
17          UPI
18         Card
20          UPI
21         Card
23          UPI
25         Cash
26          UPI
27         Card
29          UPI
30         Card
32          UPI
35          UPI
37         Cash
38          UPI
39         Card
41          UPI
42         Card
44          UPI
46         Cash
49         Cash

In [108]:
print(df[df["Rating"] .between(4.0,4.5)])

    Order_ID     Product     Category     City  Sales  Quantity  Rating  \
0       1001      Laptop  Electronics   Jaipur  55000         5     4.5
1       1002       Mouse  Accessories    Delhi   2500        10     4.0
3       1004    Notebook        Books     Pune   1800        15     4.2
5       1006  Book Stand        Books    Delhi   6500         6     4.1
6       1007  Headphones  Electronics   Mumbai   8500         7     4.3
10      1011  Laptop Bag  Accessories    Delhi   7500         6     4.2
11      1012        Book        Books   Mumbai   3500        12     4.0
12      1013      Webcam  Electronics     Pune   9500         7     4.4
13      1014       Chair    Furniture   Jaipur  15000         3     4.5
15      1016    Notebook        Books  Kolkata   2500         5     4.1
17      1018    Keyboard  Accessories   Jaipur   5000         8     4.0
19      1020     Monitor  Electronics     Pune  27000         4     4.5
20      1021  Book Shelf        Books   Mumbai   7000         7     4.2
21      1022  Headphones  Electronics  Kolkata   9000         6     4.1
25      1026  Laptop Bag  Accessories   Mumbai   6500         8     4.0
26      1027        Book        Books   Jaipur   3200        10     4.3
27      1028      Webcam  Electronics    Delhi  11000         6     4.5
29      1030        Desk    Furniture     Pune  13000         5     4.1
30      1031    Keyboard  Accessories   Jaipur   5200         8     4.0
33      1034    Notebook        Books     Pune   2200        14     4.2
35      1036  Book Stand        Books   Jaipur   5500         9     4.1
37      1038  Headphones  Electronics   Mumbai  10500         5     4.4
41      1042        Book        Books   Mumbai   4000         8     4.0
42      1043      Webcam  Electronics   Jaipur  12500         5     4.3
43      1044       Chair    Furniture     Pune  16000         3     4.5
44      1045        Desk    Furniture  Kolkata  14000         6     4.1
46      1047    Keyboard  Accessories    Delhi   4800         7     4.2
48      1049    Notebook        Books     Pune   2000        12     4.0

   Payment_Mode
0           UPI
1          Cash
3           UPI
5          Cash
6           UPI
10         Card
11          UPI
12         Cash
13         Card
15         Cash
17          UPI
19         Cash
20          UPI
21         Card
25         Cash
26          UPI
27         Card
29          UPI
30         Card
33         Card
35          UPI
37         Cash
41          UPI
42         Card
43         Cash
44          UPI
46         Cash
48         Card

In [109]:
print(df[df["Sales"] .between(10000,30000)])

    Order_ID     Product     Category     City  Sales  Quantity  Rating  \
7       1008     Printer  Electronics  Kolkata  22000         3     3.9
8       1009      Tablet  Electronics     Pune  28000         5     4.6
13      1014       Chair    Furniture   Jaipur  15000         3     4.5
14      1015        Desk    Furniture    Delhi  12000         4     3.8
19      1020     Monitor  Electronics     Pune  27000         4     4.5
22      1023     Printer  Electronics   Jaipur  21000         3     3.8
23      1024      Tablet  Electronics    Delhi  26000         5     4.6
27      1028      Webcam  Electronics    Delhi  11000         6     4.5
28      1029       Chair    Furniture  Kolkata  14500         4     3.9
29      1030        Desk    Furniture     Pune  13000         5     4.1
34      1035     Monitor  Electronics  Kolkata  30000         4     4.7
36      1037     Printer  Electronics    Delhi  19500         3     3.9
37      1038  Headphones  Electronics   Mumbai  10500         5     4.4
38      1039      Tablet  Electronics     Pune  24000         7     4.6
42      1043      Webcam  Electronics   Jaipur  12500         5     4.3
43      1044       Chair    Furniture     Pune  16000         3     4.5
44      1045        Desk    Furniture  Kolkata  14000         6     4.1
47      1048     Monitor  Electronics   Mumbai  29000         4     4.7

   Payment_Mode
7          Card
8           UPI
13         Card
14          UPI
19         Cash
22         Cash
23          UPI
27         Card
28         Cash
29          UPI
34         Cash
36         Card
37         Cash
38          UPI
42         Card
43         Cash
44          UPI
47          UPI

In [112]:
print(df.iloc[0])

Order_ID               1001
Product              Laptop
Category        Electronics
City                 Jaipur
Sales                 55000
Quantity                  5
Rating                  4.5
Payment_Mode            UPI
Name: 0, dtype: object

In [113]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["Aman", "Riya", "Neha", "Rahul", "Priya", "Karan", "Sneha", "Vikas"],
    "City": ["Jaipur", "Delhi", "Mumbai", "Jaipur", "Pune", "Delhi", "Mumbai", "Kota"],
    "Department": ["Sales", "HR", "IT", "Finance", "Sales", "IT", "HR", "Finance"],
    "Salary": [35000, 42000, 50000, 38000, 45000, 55000, 40000, 36000],
    "Experience": [2, 4, 5, 3, 4, 6, 3, 2],
    "Performance": [78, 85, 92, 74, 88, 95, 81, 76]
})

df.index = ["E101", "E102", "E103", "E104", "E105", "E106", "E107", "E108"]

print(df)

     Employee    City Department  Salary  Experience  Performance
E101     Aman  Jaipur      Sales   35000           2           78
E102     Riya   Delhi         HR   42000           4           85
E103     Neha  Mumbai         IT   50000           5           92
E104    Rahul  Jaipur    Finance   38000           3           74
E105    Priya    Pune      Sales   45000           4           88
E106    Karan   Delhi         IT   55000           6           95
E107    Sneha  Mumbai         HR   40000           3           81
E108    Vikas    Kota    Finance   36000           2           76

In [115]:
print(df.iloc[0])

Employee         Aman
City           Jaipur
Department      Sales
Salary          35000
Experience          2
Performance        78
Name: E101, dtype: object

In [116]:
print(df.iloc[-1])

Employee         Vikas
City              Kota
Department     Finance
Salary           36000
Experience           2
Performance         76
Name: E108, dtype: object

In [127]:
print(df.iloc[0,0])

Aman

In [130]:
print(df.iloc[4,3])

45000

In [136]:
print(df.loc[["E104","E105","E106"]])

     Employee    City Department  Salary  Experience  Performance
E104    Rahul  Jaipur    Finance   38000           3           74
E105    Priya    Pune      Sales   45000           4           88
E106    Karan   Delhi         IT   55000           6           95

In [ ]:
103 ,107 ,name salary

In [143]:
print(df.loc[["E103","E107"],["Employee","Salary","Department"]])

     Employee  Salary Department
E103     Neha   50000         IT
E107    Sneha   40000         HR

In [141]:
print(df.loc[["E103", "E107"], 
["Employee", "Salary", "Department"]])

     Employee  Salary Department
E103     Neha   50000         IT
E107    Sneha   40000         HR